### ISSUE TITLE
mod_shib configuration error

### ISSUE THREAD

**Issue by newlukai** [ubc/moodle-docker#11]
I recently updated the image and reset the Moodle database to get a fresh installation. The setup itself runs fine but Apache can't start the Shibboleth module due to a configuration error:

```
[Thu Sep 02 16:21:49.310673 2021] [mod_shib:crit] [pid 365] child_init: mod_shib failed to load configuration: XML error(s) during parsing, check log for specifics
[Thu Sep 02 16:21:51.296460 2021] [mod_shib:crit] [pid 373] child_init: mod_shib failed to load configuration: XML error(s) during parsing, check log for specifics
[Thu Sep 02 16:21:52.265094 2021] [mod_shib:crit] [pid 375] child_init: mod_shib failed to load configuration: XML error(s) during parsing, check log for specifics
[Thu Sep 02 16:21:52.271490 2021] [mod_shib:crit] [pid 376] child_init: mod_shib failed to load configuration: XML error(s) during parsing, check log for specifics
```

I'm quite lost regarding the Shibboleth configuration and I'm wondering if someone else also encounters this situation?

**Comment by xcompass** [comment]
Hi @newlukai, the error you saw is caused by incorrect shibboleth yaml configuration. You should check the file to see if there is anything missing. Most likely caused by database configuration. By default, the shibd/mod_shib is configured to use DB as storage service so the session can be shared between multiple container. You will have to set SHIBD_ODBC_XXX env vars to populate the correct shibboleth2.yaml. Or switch back to memory as StorageService: https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065334626/StorageService. Hope it helps.

**Comment by newlukai** [comment]
For my scenario I was able to use an older version of the image which didn't include Shibboleth.
